name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    if: ${{ contains(github.event.head_commit.message, '[run ci]') || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Saving cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          npm install

      - name: Check linting
        run: npm run lint

      - name: Check TS
        run: npm run check-ts

      # - name: Check tests
      #   run: |
      #     npm run test
